### ISSUE TITLE
Doesn't work with 8088

### ISSUE THREAD

**Issue by thamesynne** [fuzzballcat/milliForth#1]
As things stand, this doesn't quite work on an IBM PC - but making it work is easy, and costs only 2 bytes in the final size.

The main culprits:

0=, which is defined using setnz - an alternative coding is
```
    pop ax
    sub ax,1
    sbb ax,ax
    push ax
```
which is 2 bytes smaller and works on everything.

Four instances of `push word <CONSTANT>`, at lines 75, 79, 121 and 124, which only appeared on the 186 - these can be replaced by
```
    mov ax,CONSTANT
    push ax
```
These cost a byte each, which makes the final executable 2 bytes larger.

But this can be offset! Moving DOCOL to before @ and inlining NEXT at the end of STATE saves another 3 bytes (2 from the JMP and 1 because the JMP NEXT at the end of `;` is now within short range), which decreases the size to 421 bytes overall.

**Comment by thamesynne** [comment]
Also, moving getline above tok and allowing it to fall through would save 2 more bytes.

**Comment by fuzzballcat** [comment]
I've implemented the compactness suggestions.  It's even smaller now, thanks!

**Comment by mitchblank** [comment]
I think after the recent changes, there is only one `push word <CONSTANT>` remaining (in the `state@` code) so it would be relatively simple to make this an `%ifdef`
i.e.
```nasm
%ifdef SUPPORT_8086
     mov ax,STATE
     push ax
%else
     push word STATE
%endif
```
...assuming that's still the only thing that is assuming 80186-or-later

**Comment by fuzzballcat** [comment]
There is now a command `make with options="-D COMPATIBLE_8088"` which should work for 8086.
