### ISSUE TITLE
readme needs updating

### ISSUE THREAD

**Issue by peterferrie** [fuzzballcat/milliForth#16]
in Language section, "0=" should be "0#" with reversed behaviour.

**Comment by fuzzballcat** [comment]
Hey, sorry that I completely ignored this repo for over a month but thank you very much for that catch, fixed!

**Comment by fuzzballcat** [comment]
Hey, sorry that I completely ignored this repo for over a month but thank you very much for that catch, fixed!

**Comment by peterferrie** [comment]
It's all good. :-)
I thank you.

**Comment by peterferrie** [comment]
Ha, it's actually 328 bytes now, beating SectorLisp by 108 bytes.
