### ISSUE TITLE
`%ifdef` should be used

### ISSUE THREAD

**Issue by mitchblank** [fuzzballcat/milliForth#3]
There are currently two things that require editing `sector.asm` to change:

1. the commented-out "QOL improvement" of backspace
2. removing the `db` statements at the end if you want `make sizecheck` to work

yasm supports `%ifdef` though, so why not use that? https://www.tortall.net/projects/yasm/manual/html/nasm-macro-conditional.html#nasm-macro-ifdef

It supports `-D` on the command line just like `cc` ( https://www.tortall.net/projects/yasm/manual/html/yasm-options.html#yasm-preprocessor-options ) so `make sizecheck` could work automatically

If you wanted it would even be easy to fix #1 as a command-line option as well

**Comment by fuzzballcat** [comment]
Fixed, makefile streamlined.  Thanks!
