### ISSUE TITLE
`-1` is unnecessarily complicated and slow

### ISSUE THREAD

**Issue by mitchblank** [fuzzballcat/milliForth#7]
Right now hello_world.FORTH implements `-1` like:
```forth
: dup sp@ @ ;
: -1 dup dup nand dup dup nand nand ;
```

So the definition `-1` uses `dup dup` to create two copies of an arbitrary "don't care" value to pass to.  This is a little dubious if the stack is empty when it is called though.

Obviously in the bootloader we're not worried about memory protection.  However, `dup` isn't even the fastest way of pushing a "don't care" constant onto the stack.   It could instead do:
```
: -1 state@ state@ nand state@ nand ;
```
...which doesn't do any icky read-below-stack operations and should be faster -- it uses only primitive words and is shorter.

**Comment by mitchblank** [comment]
Or of course:
```
: -1 s@ s@ nand s@ nand ;
```
...after your most recent changes

**Comment by fuzzballcat** [comment]
This definition of `-1` is a holdover from the 1996 Usenet thread which in turn inspired sectorFORTH.  I frankly hadn't looked at it at all.

Thanks for this, I have changed it!

**Comment by thamesynne** [comment]
just as a note, it can be made simpler still now: `: -1 s@ 0# ;`
